window.PRESENTATION = {
  slides: [
    {
      id: 'copy', title: 'Цифрлық пираттық', theme: 'acid', name: 'Бейресми қолжетімділік',
      notes: '<p>Бұл зерттеу Қазақстан оқушыларының бейресми цифрлық контентті пайдалануын қарастырады. Негізгі сұрақ: құқықтық бағасы анық болмаған кезде бұл тәжірибенің күнделікті әдетке айналуын қандай әлеуметтік және жағдайлық механизмдер түсіндіруі мүмкін?</p><p>«Бейресми көз» деген сауалнама санаты әр әрекеттің құқықтық мәртебесін жеке анықтамайды. Тегін контенттің бәрі заңсыз емес. Заңдылық автордың рұқсатына, пайдалану тәсіліне және заңдағы ерекшеліктерге байланысты.</p>',
      html: `<div class="cover-copy"><div class="eyebrow reveal">Әлеуметтанулық зерттеу · Астана, 2026</div><h1 class="cover-title"><span class="title-line"><span>Цифрлық</span></span><span class="title-line"><span>пираттық</span></span></h1><div class="cover-sub reveal"><p>Күнделікті тәжірибе мен<br>қоғамдық мақұлдаудың арасы</p><span class="cover-slash" aria-hidden="true">/</span><p class="cover-question">Бейресми контентке<br>неге қайта ораламыз?</p></div></div><div class="disc-stage" aria-hidden="true"><img class="disc disc-echo" src="assets/disc.webp" alt=""><img class="disc disc-main" src="assets/disc.webp" alt=""></div><div class="cover-bottom reveal"><span>Қазақстан оқушылары · 14–18 жас</span><button class="start-button" data-next>Зерттеуді ашу <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M5 16h21m-8-8 8 8-8 8"/></svg></button></div>`
    },
    {
      id:'sample',title:'19 088 оқушы',theme:'ink',name:'Зерттеудің негізі',
      notes:'<p>Негізгі сандық дерек — Qazpatent сауалнамасы. Ол 2023 жылғы 3 қазаннан 10 қарашаға дейін онлайн жүргізілді. Сілтеме өңірлердің білім басқармалары арқылы таратылған. Қатысушылар — 14–18 жастағы 19 088 оқушы.</p><p>Бұл — бастапқы сауалнама жүргізу емес, жарияланған деректерді екінші рет талдау және рецензияланған әдебиетті тақырыптық синтездеу. Іріктеу кездейсоқ ықтималдық әдіспен жүргізілмеген. Үлкен қатысушылар саны барлық Қазақстан оқушыларына автоматты түрде өкілдік бермейді.</p><p>Жарияланған жиынтық көрсеткіштер бір адамның білімі, бағасы және әрекеті арасында байланыс орнатуға мүмкіндік бермейді.</p><p class="note-source">Qazpatent, 2023 · 1–3-беттер</p>',
      html:`<div class="eyebrow reveal">Qazpatent · Қазақстан · 2023</div><h2 class="sample-number" aria-label="19 088 оқушы"><span data-count="19088">19 088</span><span class="sample-unit reveal">оқушы</span></h2><div class="sample-facts"><div class="reveal"><span class="fact-number">14–18</span><span>жас</span></div><div class="reveal"><span class="fact-number">17 + 3</span><span>облыс және республикалық қала</span></div><div class="reveal"><span class="fact-number">Екінші талдау</span><span>сауалнама деректері + ғылыми әдебиет</span></div></div><div class="sample-line reveal"><span class="hairline"></span><p>Ауқымды дерек. Бірақ кездейсоқ іріктеу емес.</p><span class="source-mark">[1] · 1–3-б.</span></div>`
    },
    {
      id:'knowledge',title:'Термин таныс, жағдай түсініксіз',theme:'paper',name:'Құқықтық бағалау',
      notes:'<p>74,4% «авторлық құқық» терминін түсінетінін айтты. Бұл білім тестінің нәтижесі емес, респонденттің өзіндік бағасы.</p><p>Бейресми көзден контент алу немесе қарау заңды ма деген сұрақта 28,6% «заңсыз», 22,6% «заңды», 38% «білмеймін», 10,8% «жауап бермеймін» деді. Екі сұрақтың жиынтық нәтижесін жеке адам деңгейінде байланыстыруға болмайды.</p><p>Мұны «құқықтық нигилизм» деп түсіндіру асығыс болар еді. Нәтиже жалпы ұғымды білу мен күнделікті жағдайды жіктеу арасында зерттелуі тиіс алшақтық бар екенін көрсетеді.</p><p class="note-source">Qazpatent · 6 және 13-беттер · N = 19 088</p>',
      html:`<div class="legal-header"><h2 class="slide-title reveal">Термин таныс,<br>жағдай түсініксіз</h2><p class="side-caption reveal">Авторлық құқықты білу<br>оны қолдана білумен<br>бірдей өлшем емес</p></div><div class="knowledge-pair"><div class="knowledge-stat"><div class="stat-number"><span data-decimal="74.4">74,4</span><sup>%</sup></div><p class="reveal">«Авторлық құқық»<br>терминін түсінемін</p><span class="stat-type reveal">Өзіндік баға</span></div><div class="knowledge-stat focal"><div class="stat-number"><span data-decimal="28.6">28,6</span><sup>%</sup></div><p class="reveal">Бейресми көзден алу<br>заңсыз деп санаймын</p><span class="stat-type reveal">Нақты жағдайды бағалау</span></div></div><div class="legal-bottom reveal"><div class="legal-distribution" aria-label="Құқықтық баға: заңсыз 28,6%; заңды 22,6%; білмеймін 38%; жауап жоқ 10,8%"><span>28,6% <small>Заңсыз</small></span><span>22,6% <small>Заңды</small></span><span class="unknown-label">38% <small>Білмеймін</small></span><span>10,8% <small>Жауап жоқ</small></span></div><p class="data-caveat">Жиынтық деректер. Бір адамның жауаптары байланыстырылмаған.</p><span class="source-mark">[1] · 6, 13-б.</span></div>`
    },
    {
      id:'practice',title:'40,7% бейресми контент пайдаланған',theme:'blue',name:'Тәжірибенің ауқымы',
      notes:'<p>40,7% соңғы 12 айда музыка, фильм, сериал, ойын немесе басқа контентті бейресми көзден пайдаланғанын хабарлады. 47% «жоқ» деді; 12,3% жауап бермеді.</p><p>Бұл көрсеткіш тәжірибенің таралуын сипаттайды. Ол бір реттік әрекет пен тұрақты әдетті ажыратпайды. Жауап бермеген 12,3%-ды жасырын пайдаланушылар деп санауға негіз жоқ.</p><p>«Қазақстан жастары — 2024» зерттеуінде 14–18 жастағылардың 59,4%-ы фильм мен сериал үшін тегін видеоплатформаларға басымдық берген. Бұл басқа сұрақ және басқа іріктеме: 40,7%-бен салыстыруға немесе уақыттық өзгеріс есептеуге болмайды.</p><p class="note-source">Qazpatent · 16-бет; «Қазақстан жастары — 2024» · 155-бет</p>',
      html:`<div class="practice-head reveal"><span class="eyebrow">Соңғы 12 ай · Qazpatent, 2023</span><h2>Бейресми контент<br>цифрлық тәжірибеде бар</h2></div><div class="practice-number"><span data-decimal="40.7">40,7</span><sup>%</sup></div><div class="practice-side reveal"><p>пайдаланғанын<br>хабарлады</p><span>Бұл — таралу көрсеткіші.<br>Жиілігі мен мақұлдауы өлшенбеген.</span></div><div class="practice-chart"><div class="stacked-bar" role="img" aria-label="Пайдаланды: 40,7%; пайдаланбады: 47%; жауап бермеді: 12,3%"><i class="segment segment-used" style="flex-basis:40.7%"></i><i class="segment segment-no" style="flex-basis:47%"></i><i class="segment segment-missing" style="flex-basis:12.3%"></i></div><div class="stacked-labels reveal"><span><b>40,7%</b> Пайдаланды</span><span><b>47%</b> Пайдаланбады</span><span><b>12,3%</b> Жауап бермеді</span></div><div class="chart-source reveal"><span>N = 19 088 · Өзіндік есеп</span><span>[1] · 16-б.</span></div></div>`
    },
    {
      id:'criteria',title:'Ыңғайлылық заңдылықтан жиі аталды',theme:'paper',name:'Қолданушының таңдауы',
      notes:'<p>Сауалнамада интернеттегі контентті пайдалану және жүктеу кезінде ең маңызды үш қасиетті таңдау сұралған. Ыңғайлылық — 9 431 жауап; қауіпсіздік — 8 927; контенттің кең таңдауы — 8 196; арзан немесе тегін болуы — 3 861; заңдылық — 3 401.</p><p>49,4%, 46,8%, 42,9% есепте берілген. 20,2% және 17,8% — жауап санын 19 088-ге бөлу арқылы есептелген жуық мәндер. Ыңғайлылық заңдылықтан шамамен 2,8 есе жиі аталды.</p><p>Бір респондент үш нұсқа таңдағандықтан, пайыздардың қосындысы 100%-ға тең болмауы тиіс. Сұрақ жалпы интернет-контент туралы қойылған. Бұл пираттықты таңдаудың себептерін тікелей өлшеу емес.</p><p class="note-source">Qazpatent · 12-бет · N = 19 088 · үш жауапқа дейін</p>',
      html:`<div class="criteria-heading"><div><span class="eyebrow reveal">Интернет-көздің маңызды қасиеттері</span><h2 class="slide-title reveal">Ыңғайлылық<br>жиі аталады</h2></div><div class="ratio-callout reveal"><span>≈2,8×</span><p>заңдылықпен<br>салыстырғанда</p></div></div><div class="ranking" role="img" aria-label="Ыңғайлылық 49,4%; қауіпсіздік 46,8%; кең таңдау 42,9%; арзан не тегін 20,2%; заңдылық 17,8%. Нөлден басталатын 0–50% шкала."><div class="ranking-axis"><span>0</span><span>25</span><span>50%</span></div><div class="bar-row"><span class="bar-name">Ыңғайлылық</span><div class="bar-track"><i class="bar-fill bar-focal" style="width:98.8%"></i></div><span class="bar-value">49,4%</span></div><div class="bar-row"><span class="bar-name">Қауіпсіздік</span><div class="bar-track"><i class="bar-fill" style="width:93.6%"></i></div><span class="bar-value">46,8%</span></div><div class="bar-row"><span class="bar-name">Кең таңдау</span><div class="bar-track"><i class="bar-fill" style="width:85.8%"></i></div><span class="bar-value">42,9%</span></div><div class="bar-row"><span class="bar-name">Арзан не тегін</span><div class="bar-track"><i class="bar-fill" style="width:40.4%"></i></div><span class="bar-value">≈20,2%</span></div><div class="bar-row"><span class="bar-name">Заңдылық</span><div class="bar-track"><i class="bar-fill" style="width:35.6%"></i></div><span class="bar-value">≈17,8%</span></div></div><div class="chart-bottom reveal"><p>Үш жауап таңдалған. Бұл — жалпы контентке қойылатын талаптар.</p><span class="source-mark">[1] · 12-б. · N = 19 088</span></div>`
    },
    {
      id:'norms',title:'Жиі кездесуі мақұлданғанын білдірмейді',theme:'acid',name:'Зерттеудің негізгі шегі',
      notes:'<p>Сипаттамалық норма — адамның айналасында әрекет қаншалықты таралған деп ойлайтыны. Мақұлдау нормасы — айналасындағылар сол әрекетті қаншалықты қолдайды деп ойлайтыны. Бұлар бір ұғым емес.</p><p>Адам әрекетті кең таралған, бірақ құпталмайтын деп санауы мүмкін. Немесе жалпы ережені сақтай отырып, белгілі бір жағдайға ерекше рұқсат беруі мүмкін.</p><p>Қазақстандағы қарастырылған сауалнамаларда достардың мақұлдауы, жеке моральдық баға және қабылданған әлеуметтік норма өлшенбеген. Сондықтан «оқушылар пираттықты қалыпты деп санайды» деген тұжырымды бұл дерек дәлелдемейді.</p><p class="note-source">Cho, Chung & Filippova, 2015; қазақстандық сауалнамалардың өлшеу шектеулері</p>',
      html:`<span class="eyebrow reveal">Таралу мен мақұлдау — екі бөлек өлшем</span><div class="norm-composition"><h2><span class="norm-word first-norm reveal">Жиі<br>кездеседі</span><span class="not-equal reveal" aria-label="тең емес">≠</span><span class="norm-word second-norm reveal">Құпталады</span></h2></div><div class="norm-annotations"><p class="reveal"><span class="annotation-rule"></span>Айналамда не істейді?</p><p class="reveal"><span class="annotation-rule"></span>Айналамда нені қолдайды?</p></div><div class="norm-bottom reveal"><strong>Қоғамдық мақұлдау бұл сауалнамаларда өлшенбеген</strong><span class="source-mark">[5] + [1], [2]</span></div>`
    },
    {
      id:'mechanisms',title:'Таңдауға бірнеше механизм ықпал етуі мүмкін',theme:'ink',name:'Үш ықтимал механизм',
      notes:'<p>Бұл слайд Қазақстанда дәлелденген себептерді емес, зерттеуге лайық ықтимал механизмдерді көрсетеді.</p><p>Құқықтық белгісіздік: термин таныс болса да, нақты көздің құқықтық мәртебесін анықтау қиын. Бұл механизмге жергілікті сипаттамалық дерек тікелей негіз береді.</p><p>Сервистің логикасы: баға, каталог, ыңғайлылық және үйреншікті кіру жолы бірге әрекет етуі мүмкін. Qazpatent критерийлері және Kim & Kim зерттеуі осы гипотезаны қолдайды.</p><p>Әлеуметтік орта мен ақтау: достардың әрекеті, күтілетін мақұлдау және «бұл жағдайда зиян жоқ» сияқты түсіндірулер жалпы нормадан ерекшелік жасауға көмектесуі мүмкін. Borja et al. және Aydın еңбектері маңызды, бірақ жергілікті механизм өлшенбеген.</p><p>Мета-талдау 174 зерттеудегі 1 373 әсерді жинақтайды. Нәтиже бір ғана баға немесе бір ғана білім арқылы түсіндіруге болмайтынын көрсетеді. Мәдени контекст әсердің күшін өзгертеді.</p><p class="note-source">[6] Eisend; [7] Borja et al.; [9] Kim & Kim; [10] Aydın</p>',
      html:`<div class="mechanisms-heading"><h2 class="slide-title reveal">Таңдау қалай<br>қалыптасады?</h2><p class="reveal">Бір себепке сыймайтын тәжірибе<br><span>Қазақстанда тексерілуі тиіс гипотезалар</span></p></div><div class="mechanism-accordion"><button class="mechanism-panel is-expanded" aria-expanded="true" data-mechanism="0"><span class="mechanism-order">01</span><h3>Құқықтық<br>белгісіздік</h3><div class="mechanism-detail"><p>«Бұл көзге рұқсат бар ма?»</p><span>Ұғымды білу нақты жағдайды<br>ажыратуға жеткіліксіз болуы мүмкін.</span><div class="mechanism-state">Жергілікті деректе байқалады</div></div><span class="mechanism-plus" aria-hidden="true">−</span></button><button class="mechanism-panel" aria-expanded="false" data-mechanism="1"><span class="mechanism-order">02</span><h3>Сервистің<br>логикасы</h3><div class="mechanism-detail"><p>«Қай жол ыңғайлы?»</p><span>Баға, қолжетімділік, каталог<br>және үйреншікті маршрут.</span><div class="mechanism-state">Ықтимал түсіндіру</div></div><span class="mechanism-plus" aria-hidden="true">+</span></button><button class="mechanism-panel" aria-expanded="false" data-mechanism="2"><span class="mechanism-order">03</span><h3>Орта<br>және ақтау</h3><div class="mechanism-detail"><p>«Достарым да қарайды»</p><span>Әлеуметтік күтулер мен<br>жағдайлық ерекшелік жасау.</span><div class="mechanism-state">Қазақстанда өлшенбеген</div></div><span class="mechanism-plus" aria-hidden="true">+</span></button></div><p class="mechanism-footer reveal">Шетелдегі байланыстар Қазақстан оқушылары үшін дайын себеп емес <span class="source-mark">[6]–[10]</span></p>`
    },
    {
      id:'habit',title:'Баға төмендеді, тікелей кіру өзгермеді',theme:'coral',name:'Баға және әдет',
      notes:'<p>Rajavi, Danaher және Newby электронды кітаптардың заңды бағасы өзгерген табиғи экспериментті талдады. Заңды баға 14%-ға төмендеді.</p><p>Пираттық сайттарға іздеу жүйесі арқылы кіру 27%-ға азайды. Тікелей кіру өзгермеді. Пираттық кірудің жалпы санының төмендеуі статистикалық маңызды болмады.</p><p>Бұл — Қазақстан оқушылары туралы нәтиже емес. Ол баға таңдау сәтіне ықпал етуі мүмкін, ал бұрын қалыптасқан маршрутқа ықпалы шектеулі болуы мүмкін деген гипотезаны нақтылайды.</p><p class="note-source">Rajavi, Danaher & Newby, 2024 · MIS Quarterly · DOI: 10.25300/MISQ/2024/18466</p>',
      html:`<div class="habit-header"><span class="eyebrow reveal">Электронды кітаптар · шетелдегі табиғи эксперимент</span><h2 class="slide-title reveal">Баға төмендеді,<br>тікелей кіру өзгермеді</h2></div><div class="price-sequence"><div class="price-main"><span class="price-value reveal">−14<sup>%</sup></span><p class="reveal">заңды баға</p></div><div class="route-results"><div class="route-result reveal"><div><span class="route-tag">Іздеу арқылы кіру</span><p>Таңдау сәті</p></div><strong>−27%</strong></div><div class="route-result reveal"><div><span class="route-tag">Тікелей кіру</span><p>Үйреншікті жол</p></div><strong class="unchanged">Өзгермеді</strong></div></div></div><div class="habit-bottom reveal"><p>Жалпы пираттық кірудің төмендеуі статистикалық маңызды болмады.</p><span class="source-mark">[8] · Rajavi et al., 2024</span></div>`
    },
    {
      id:'scenarios',title:'Бір әрекет, бес түрлі жағдай',theme:'paper',name:'Келесі зерттеу қадамы',
      notes:'<p>Бұл — қосымшадағы жоспарланған сценарийлік сауалнаманың интерактивті үлгісі. Ол жүргізілген зерттеудің нәтижесі емес. Интерфейс жауаптарды серверге жібермейді, тек осы бетте уақытша көрсетеді.</p><p>Қатысушы өзінің әрекетін емес, ойдан шығарылған кейіпкердің шешімін бағалайды. Базалық сценарийде фильм заңды және қолжетімді, бірақ кейіпкер бейресми тегін көзді таңдайды. Кейін қолжетімсіздік, жоғары баға, достар ортасы және авторға айқын қолдау шарттары жеке өзгертіледі.</p><p>Болашақ сауалнамада қабылдауға болатындық пен құрдастардың ықтимал әрекеті бөлек сұралады. Бағалау шкаласы — 1–7. Сценарийлердің ретін кері нұсқамен теңгеру ұсынылады.</p><p>Талдау: әр адамның B–E бағаларын A-мен салыстыру; медианалар мен таралулар; жеткілікті іріктемеде жұптық Уилкоксон критерийі және әсер мөлшері. Бұл бетте статистикалық талдау жүргізілмейді.</p><p class="note-source">Зерттеу құжаты · А қосымшасы</p>',
      html:`<div class="scenario-heading"><span class="eyebrow reveal">Сценарийлік сауалнама жобасы</span><h2 class="slide-title reveal">Бір әрекет.<br>Бес түрлі жағдай.</h2></div><div class="scenario-lab"><div class="scenario-tabs" role="tablist" aria-label="Жағдайды таңдау"><button role="tab" aria-selected="true" aria-controls="scenario-panel" id="scenario-tab-0" data-scenario="0" tabindex="0"><span>A</span> Базалық</button><button role="tab" aria-selected="false" aria-controls="scenario-panel" id="scenario-tab-1" data-scenario="1" tabindex="-1"><span>B</span> Қолжетімсіз</button><button role="tab" aria-selected="false" aria-controls="scenario-panel" id="scenario-tab-2" data-scenario="2" tabindex="-1"><span>C</span> Қымбат</button><button role="tab" aria-selected="false" aria-controls="scenario-panel" id="scenario-tab-3" data-scenario="3" tabindex="-1"><span>D</span> Достар</button><button role="tab" aria-selected="false" aria-controls="scenario-panel" id="scenario-tab-4" data-scenario="4" tabindex="-1"><span>E</span> Авторға қолдау</button></div><div id="scenario-panel" class="scenario-panel" role="tabpanel" aria-labelledby="scenario-tab-0"><p id="scenario-condition">Фильм Қазақстанда заңды түрде қолжетімді. Бағасы орынды.</p><p class="scenario-action">Кейіпкер оны бейресми тегін сайттан қарайды.</p></div><div class="scenario-rating"><label id="rating-label">Қаншалықты қабылдауға болады?</label><div class="rating-buttons" role="group" aria-labelledby="rating-label">${[1,2,3,4,5,6,7].map(n=>`<button data-rating="${n}" aria-pressed="false" aria-label="${n} балл">${n}</button>`).join('')}</div><div class="scale-labels"><span>Мүлде қабылданбайды</span><span>Толық қабылданады</span></div><div class="rating-status" id="rating-status" aria-live="polite">Бағаңызды таңдаңыз</div></div></div><div class="scenario-footer reveal"><p>Бұл — зерттеу құралының үлгісі. Жауаптар жиналмайды.</p><span class="source-mark">А қосымшасы</span></div>`
    },
    {
      id:'actions',title:'Нақты жағдайды түсіндіру және заңды жолды жеңілдету',theme:'blue',name:'Практикалық бағыттар',
      notes:'<p>Бірінші ұсыныс: авторлық құқықтың анықтамасын жаттатумен шектелмей, нақты жағдайларды ажыратуды үйрету. Ресми сервис, лицензияланған тегін көз, рұқсатсыз көшірме және заңда рұқсат етілген пайдалану бірдей емес.</p><p>Екінші ұсыныс: заңды жолдың ыңғайлылығы мен қолжетімділігін жақсарту. Ақпараттық науқан каталог, баға және интерфейс мәселелерін жалғыз өзі шешпейді.</p><p>Үшінші ұсыныс: әлеуметтік нормалар туралы хабарламаны абайлап құрастыру. Whitman & Cox тәжірибесінде норманың таралуы жөніндегі ақпарат кейбір ер қатысушыларда пираттық ниетін арттырған. «Мұны көп адам істейді» деген сөз әрекетті қалыпты етіп көрсетуі мүмкін.</p><p>Бұл ұсыныстардың Қазақстандағы әсері тексерілген жоқ. Олар дерек пен әдебиет негізіндегі практикалық бағыттар.</p><p class="note-source">[1], [9], [11] · Ұсыныстар, жергілікті әсері өлшенбеген</p>',
      html:`<span class="eyebrow reveal">Дерек пен әдебиеттен шығатын ұсыныстар</span><h2 class="slide-title reveal">Нақты таңдауға<br>ықпал ету</h2><div class="action-list"><div class="action-row reveal"><span class="action-index">01</span><h3>Жағдаймен үйрету</h3><p>Анықтамадан бөлек, лицензияланған көзді<br>рұқсатсыз көшірмеден ажырату.</p></div><div class="action-row reveal"><span class="action-index">02</span><h3>Заңды жолды жеңілдету</h3><p>Қолжетімді каталог, орынды баға<br>және ыңғайлы кіру жолы.</p></div><div class="action-row reveal"><span class="action-index">03</span><h3>Норманы абайлап жеткізу</h3><p>«Бәрі солай істейді» деген хабарламаның<br>кері әсерін ескеру.</p></div></div><div class="action-bottom reveal"><p>Ұсыныстардың Қазақстандағы әсері әлі тексерілген жоқ</p><span class="source-mark">[1], [9], [11]</span></div>`
    },
    {
      id:'conclusion',title:'Әдеттің таралуы мақұлдауды дәлелдемейді',theme:'acid',name:'Негізгі қорытынды',
      notes:'<p>Дерек көрсететін үш нәрсе: бейресми контентті пайдалану — елеулі тәжірибе; құқықтық мәртебе туралы қолданбалы баға көптеген респондент үшін белгісіз; интернет-көздің ыңғайлылығы, қауіпсіздігі және таңдауы заңдылықтан жиі аталады.</p><p>Дерек көрсетпейтін нәрсе: оқушылардың қоғамдық немесе жеке моральдық мақұлдауы; әр механизмнің себептік үлесі; бір реттік пайдалану мен тұрақты әдеттің айырмасы.</p><p>Тұжырым: тәжірибе әдетке айналуы мүмкін, бірақ мақұлданғанын анықтау үшін нормаларды, жағдайлық ерекшеліктерді және қабылданған зиянды бөлек өлшеу қажет. Келесі қадам — бір әрекетті әртүрлі жағдайларда бағалататын жергілікті сценарийлік зерттеу.</p>',
      html:`<span class="eyebrow reveal">Зерттеудің негізгі қорытындысы</span><h2 class="conclusion-title"><span class="title-line"><span>Әдеттің таралуы</span></span><span class="title-line"><span>мақұлдауды</span></span><span class="title-line"><span>дәлелдемейді</span></span></h2><div class="conclusion-disc" aria-hidden="true"><img src="assets/disc.webp" alt=""></div><div class="conclusion-bottom"><p class="reveal">Келесі қадам — әлеуметтік норманы,<br>жағдайлық ақтауды және зиянды бөлек өлшеу.</p><button class="conclusion-source reveal" data-open-sources>Дереккөздерді қарау <span aria-hidden="true">↗</span></button></div>`
    }
  ],
  sources:[
    '<strong>[1] Qazpatent · 2023 / 2024</strong>Орта білім беру ұйымдары оқушыларының зияткерлік меншік туралы сауалнамасы. N = 19 088, 14–18 жас. Сауалнама: 03.10–10.11.2023; жариялау: 05.04.2024. <a href="https://qazpatent.kz/storage/app/media/%20%D1%88%D0%BA%D0%BE%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%B8.pdf" target="_blank" rel="noopener noreferrer">Толық есеп · PDF</a>',
    '<strong>[2] «Қазақстан жастары — 2024»</strong>«Жастар» ғылыми-зерттеу орталығы. «Жастардың тұтыну мәдениеті» бөлімі, 155-бет. N = 2 000, 14–34 жас; 14–18 жас тобының тегін видеоплатформаларды таңдауы — 59,4%. Негізгі презентацияда басқа көрсеткішпен тікелей салыстырылмайды.',
    '<strong>[3] ҚР Мәдениет және ақпарат министрлігі · 2024</strong>«80% казахстанской молодежи считают семью главной ценностью». «Қазақстан жастары» нәтижелері туралы ресми хабарлама, 13.08.2024.',
    '<strong>[4] ҚР «Авторлық құқық және сабақтас құқықтар туралы» заңы</strong>10.06.1996, № 6-I. 16, 18, 19, 26-баптар. <a href="https://adilet.zan.kz/kaz/docs/Z960000006_" target="_blank" rel="noopener noreferrer">Әділет · заң мәтіні</a>',
    '<strong>[5] Cho, Chung & Filippova · 2015</strong>Perceptions of social norms surrounding digital piracy. Computers in Human Behavior, 48, 506–515. <a href="https://doi.org/10.1016/j.chb.2015.02.018" target="_blank" rel="noopener noreferrer">DOI: 10.1016/j.chb.2015.02.018</a>',
    '<strong>[6] Eisend · 2019</strong>Explaining Digital Piracy: A Meta-Analysis. Information Systems Research, 30(2), 636–664. <a href="https://doi.org/10.1287/isre.2018.0821" target="_blank" rel="noopener noreferrer">DOI: 10.1287/isre.2018.0821</a>',
    '<strong>[7] Borja, Rodriguez & Roby · 2024</strong>Streaming movies, series and shows: attitudes and beliefs among Gen Zers. Young Consumers, 26(1), 96–115. <a href="https://doi.org/10.1108/YC-04-2024-2057" target="_blank" rel="noopener noreferrer">DOI: 10.1108/YC-04-2024-2057</a>',
    '<strong>[8] Rajavi, Danaher & Newby · 2024</strong>Price, Piracy, and Search: Which Pirates Respond to Changes in the Legal Price? MIS Quarterly, 48(4), 1537–1558. <a href="https://doi.org/10.25300/MISQ/2024/18466" target="_blank" rel="noopener noreferrer">DOI: 10.25300/MISQ/2024/18466</a>',
    '<strong>[9] Kim & Kim · 2025</strong>Why do individuals use online video piracy websites? Computers in Human Behavior, 166, 108575. <a href="https://doi.org/10.1016/j.chb.2025.108575" target="_blank" rel="noopener noreferrer">DOI: 10.1016/j.chb.2025.108575</a>',
    '<strong>[10] Aydın · 2025</strong>How digital pirates cope with guilt and norms. Journal of Information, Communication and Ethics in Society, 23(3), 367–383. <a href="https://doi.org/10.1108/JICES-08-2024-0112" target="_blank" rel="noopener noreferrer">DOI: 10.1108/JICES-08-2024-0112</a>',
    '<strong>[11] Whitman & Cox · 2025</strong>The rising tide of piracy: the influence of social roles, risks and norms on illegal consumption. Frontiers in Behavioral Economics, 4, 1631329. <a href="https://doi.org/10.3389/frbhe.2025.1631329" target="_blank" rel="noopener noreferrer">DOI: 10.3389/frbhe.2025.1631329</a>',
    '<strong>[12] Kos Koklič, Kukar-Kinney & Vida · 2026</strong>Digital piracy through the lens of moral intensity and risk perception: A cross-cultural perspective. Cyberpsychology, 20(3), Article 11. <a href="https://doi.org/10.5817/CP2026-3-11" target="_blank" rel="noopener noreferrer">DOI: 10.5817/CP2026-3-11</a>'
  ]
};
